services:
  - type: web
    name: thanhdatshop-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/products
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
